"""admin panel: disabled accounts, last seen, and a log of admin actions

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-04 00:13:17.600037

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("target_email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_actions_target_user_id"), "admin_actions", ["target_user_id"], unique=False
    )
    op.add_column("users", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Like every table (0009): out of reach of a hosted database's public API.
    op.execute("alter table public.admin_actions enable row level security")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "disabled_at")
    op.drop_column("users", "last_seen_at")
    op.drop_index(op.f("ix_admin_actions_target_user_id"), table_name="admin_actions")
    op.drop_table("admin_actions")
    # ### end Alembic commands ###
