"""ats checker

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-06 21:16:27.732799

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | Sequence[str] | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ats_checks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("mime", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("storage_key", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("job_text", sa.Text(), nullable=True),
        sa.Column("parsed_job", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ats_checks_created_at"), "ats_checks", ["created_at"], unique=False)
    # ### end Alembic commands ###
    # Like every table (0009): out of reach of a hosted database's public API.
    op.execute("alter table public.ats_checks enable row level security")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ats_checks_created_at"), table_name="ats_checks")
    op.drop_table("ats_checks")
    # ### end Alembic commands ###
